import { ToastContainer } from 'react-toastify';
import type { Metadata } from 'next'

import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

import { poppins, robotoMono } from '@/utils/fonts'
import Head from 'next/head';

export const metadata: Metadata = {
  title: 'TODO mgtk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${poppins.className} ${robotoMono.variable}`} lang="pt-br">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
      </Head>
      <body className='w-full min-h-screen bg-primary dark:bg-primary-dark'>
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
